const API_REQUEST = 'API_REQUEST';
const API_REQUEST_FAILURE = 'API_REQUEST_FAILURE';

const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';

const OPEN_MODAL = 'OPEN_MODAL';
const CLOSE_MODAL = 'CLOSE_MODAL';

export default {
  API_REQUEST,
  API_REQUEST_FAILURE,
  GET_STUDENTS_SUCCESS,
  ADD_STUDENT_SUCCESS,
  DELETE_STUDENT_SUCCESS,
  GET_TYPES_SUCCESS,
  OPEN_MODAL,
  CLOSE_MODAL,
};
